### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by ddalcino** [miurahr/aqtinstall#339]
I have several different ideas for improvements to the documentation, and I'd like to discuss them here.

### 1. More consistent names for CLI arguments.
For instance, the help text for most subcommands refers to the 'host operating system' (windows, mac, linux) as 'host'. However, the documentation refers to it as 'target OS', and the source code alternates between calling it 'host' and 'os_name'. I think it's a mistake to call it 'target OS' anywhere, because the docs refer to many CLI arguments as 'target something', and the help text refers to the next positional argument as 'target' (desktop, android, ios, winrt). There are several instances of inconsistent or confusing names that I would like to change:

* 'target OS'/'host'/'os_name' (windows, mac, linux):
I would like to call this 'host' in all places.
* 'target variant'/'target'/'target_sdk' (desktop, android, ios, winrt): 
I would like to call this 'target' in all places.
* 'target architecture'/'arch'/'architecture' (gcc_64 , clang_64, win_msvc, mingw, android_armv7, etc):
I would like to call this 'arch' in all places.
* 'tool variant name'/'arch' (qt.tools.openssl.gcc_64, qt.tools.vcredist_msvc2013_x64, qt.tools.ifw.41):
I would like to call this 'tool_variant' or 'tool_module' in all places. This argument is referred to as 'arch' in the `aqt tool` help text and the `ToolArchive` code. The names sometimes include an architecture, but they are definitely not architectures. Calling this argument 'arch' is confusing, and it clashes with the other 'arch' argument.

Honestly, I don't care what we change these names to, as long as they are consistent in the help text, code, and docs.

### 2. Subcommand formatting

When I split the `aqt list` command into `list-qt` and `list-tool`, I reformatted the docs to list a single command line option on every line, so they would be more readable. When displayed as code, they look ok:
```
.. program::  aqt

.. option:: list-qt [-h | --help]
                    [--extension <extension>]
                    [--spec <specification>]
                    [--modules    (<Qt version> | latest) |
                     --extensions (<Qt version> | latest) |
                     --arch       (<Qt version> | latest) |
                     --latest-version]
                    <target OS> [<target variant>]

    List available versions of Qt, targets, extensions, modules, and architectures.
```
However, Sphinx formats this code into this mess:

![image](https://user-images.githubusercontent.com/6743441/126909468-0a050f77-2fd2-4b15-a897-d5a51200bffb.png)

There has got to be a better way to display this. I looked at a few other projects using Sphinx to render their documentation, to see how CLI arguments were formatted, and most of them display subcommands like this as code blocks:

```
aqt list-qt [-h | --help]
            [--extension <extension>]
            [--spec <specification>]
            [--modules    (<Qt version> | latest) |
             --extensions (<Qt version> | latest) |
             --arch       (<Qt version> | latest) |
             --latest-version]
            <target OS> [<target variant>]
```

Here's one example: https://docs.conan.io/en/latest/reference/commands/consumer/install.html

The docs for the sphinx-build tool show a manpage formatted as HTML: https://www.sphinx-doc.org/en/master/man/sphinx-build.html

### 3. More links to relevant areas of the documentation.
I think it would be helpful if the docs for the `aqt install` command described how to use the `aqt list-qt` tool to find out what arguments are acceptable for `arch` and `modules`, etc., or at least provided a link to the `aqt list-qt` docs.

### 4. Keep `docs/available_versions.rst` more up-to-date.
I think that a lot of people trying to use `aqt` use the 'Available Versions' page to figure out what versions, modules, architectures, etc. to fill in the arguments for the `aqt install` command, but that file is out of date. It might be possible to use `combinations.json` or `ci/generate_combinations.py` to automatically generate this page, or at least check it for inaccuracies.

### 5. Add a short tutorial for the List commands
It's probably better to use the `aqt list` subcommands to figure out how to fill in the arguments for the `aqt install` command than to use the 'Available Versions' page. Users can figure this out on their own from the `docs/cli.rst` page, but I think a short narrative tutorial would help more.

### 6. Add 'Install-* Common Options' section

This section should contain descriptions of all the flags mentioned in https://github.com/miurahr/aqtinstall/issues/339#issuecomment-892922274

---

I would like to volunteer to make PRs for all these improvements except for 4; I think that one might be non-trivial. I will wait for some feedback before I get started though. 

I apologize if this should actually be 5 separate issues; I didn't want to spam the Issues section with 5 new issues all at once. I can split this up if you'd prefer.

---

**Edit:** Add checklist

- [X] 1. More consistent names for CLI arguments - fixed in #358
- [X] 2. Subcommand formatting - fixed in #340
- [X] 3. More links to relevant areas of the documentation. - fixed in #358
- [X] 4. Keep `docs/available_versions.rst` more up-to-date - Replaced with wiki page in #357
- [X] 5. Add a short tutorial for the List commands - added in #351
- [ ] 6. Organize `cli.rst` into `list-*` and `install-*` commands, and add 'Install-* Common Options' section

**Comment by miurahr** [comment]
> 2. Subcommand formatting

Current document uses sphinx standard domain to express command line options
https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#the-standard-domain

It has limited expressions.  It looks good for expressing each options one by one.
 Conan use `code-block:: bash` for help message style descriptions. We can do it for help message, and then detailed description can use standard domain expression.

**Comment by miurahr** [comment]
> 4. Keep docs/available_versions.rst more up-to-date.

As you warns, it become out of date. We can move these onto wiki where anyone can edit.

**Comment by miurahr** [comment]
> 5. Add a short tutorial for the List commands

We can put `getting-started` page in start of document, that use list command,  then use install command.
It can be a short tutorial.

**Comment by miurahr** [comment]
> 2. Subcommand formatting

I may have been misusing `program` and `options` directives.  #340 is a fix of  directives usage and adaption of @ddalcino proposal.

It produces a better document format and index.

![image](https://user-images.githubusercontent.com/123720/126916529-1bbb54df-be9b-4e1d-836f-98e3135820fd.png)

![image](https://user-images.githubusercontent.com/123720/126916549-5098fe77-be9c-427f-94a8-757e6a6992bb.png)

**Comment by miurahr** [comment]
> 4.. Keep docs/available_versions.rst more up-to-date.

I've added wiki page

https://github.com/miurahr/aqtinstall/wiki/Available-Qt-versions

**Comment by ddalcino** [comment]
While working on #358, I realized that there are additional command line options for several of the `install-*` subcommands that are not documented in `docs/cli.rst`.

* Entries for `install-tool`, `install-src`, install-doc`, and `install-example` are missing the following options, which are identical to their counterparts in `install-qt`:
```
  -O [OUTPUTDIR], --outputdir [OUTPUTDIR]
                        Target output directory(default current directory)
  -b [BASE], --base [BASE]
                        Specify mirror base url such as http://mirrors.ocf.berkeley.edu/qt/, 
                        where 'online' folder exist.
  --timeout [TIMEOUT]   Specify connection timeout for download site.(default: 5 sec)
  -E [EXTERNAL], --external [EXTERNAL]
                        Specify external 7zip command path.
  --internal            Use internal extractor.
  -k, --keep            Keep downloaded archive when specified, otherwise remove after install
```
* Entries for `install-src`, `install-doc`, and `install-example` are missing the following options, which are identical to their counterparts in `install-qt`:
```
  -m [MODULES ...], --modules [MODULES ...]
                        Specify extra modules to install
  --archives [ARCHIVES ...]
                        Specify subset packages to install (Default: all standard and extra modules).
```

I think it would make sense to reuse the existing documentation in the section on `install-qt` for these options, since they work the same way. However, I have not found a really good solution to this.

**Comment by miurahr** [comment]
> While working on #358, I realized that there are additional command line options for several of the install-* subcommands that are not documented in docs/cli.rst.

Good catch, thank you!

We can have two sections **LIST** commands and **INSTALL** commands, and explain common options in **INSTALL** commands. It will help us to reuse descriptions for common options.
